# Generated by Django 3.2.4 on 2021-09-09 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrepreneur',
            fields=[
                ('id', models.AutoField(db_column='id_emprendedor', primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, db_column='codigo_mies', max_length=45, null=True, unique=True)),
                ('identify', models.CharField(blank=True, db_column='identificacion', max_length=45, null=True, unique=True)),
                ('type_identify', models.CharField(blank=True, choices=[('CED', 'CEDULA'), ('RUC', 'REGISTRO ÚNICO DEL CONTRIBUYENTE'), ('PAS', 'PASAPORTE')], db_column='tipo_identificacion', max_length=45, null=True)),
                ('phone', models.CharField(blank=True, db_column='telefono', max_length=45, null=True)),
                ('barrio', models.CharField(blank=True, db_column='barrio', max_length=45, null=True)),
                ('sector', models.CharField(blank=True, db_column='sector', max_length=45, null=True)),
                ('address', models.CharField(blank=True, db_column='domicilio', max_length=45, null=True)),
                ('status', models.CharField(blank=True, db_column='status', max_length=2, null=True)),
            ],
            options={
                'db_table': 'tbl_emprendedor',
            },
        ),
    ]
