# Generated by Django 3.2.4 on 2021-09-09 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiante', '0001_initial'),
        ('emprendedor', '0001_initial'),
        ('tipo_actividad_economica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(db_column='id_usuario', primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, db_column='email', max_length=45, null=True, unique=True)),
                ('names', models.CharField(blank=True, db_column='full_name', max_length=45, null=True)),
                ('identify', models.CharField(db_column='no_identificacion', max_length=45, unique=True)),
                ('password', models.CharField(blank=True, db_column='password', max_length=128, null=True)),
                ('status', models.CharField(blank=True, db_column='status', default='A', max_length=1, null=True)),
                ('create_time', models.DateTimeField(blank=True, db_column='create_time', null=True)),
                ('last_login', models.DateTimeField(blank=True, db_column='last_login', null=True)),
                ('is_admin', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'db_table': 'tbl_usuario',
            },
        ),
        migrations.CreateModel(
            name='ActivityEconomic',
            fields=[
                ('id', models.AutoField(db_column='id_actividad_economica', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='nombre', max_length=45, null=True, unique=True)),
                ('description', models.CharField(blank=True, db_column='descripcion', max_length=45, null=True)),
                ('status', models.CharField(blank=True, db_column='status', max_length=2, null=True)),
                ('typeActEcon', models.ForeignKey(db_column='id_tipo_act_economica', on_delete=django.db.models.deletion.CASCADE, to='tipo_actividad_economica.typeactivityeconomic')),
            ],
            options={
                'db_table': 'tbl_actividad_economica',
            },
        ),
        migrations.CreateModel(
            name='Entrepreneurship',
            fields=[
                ('id', models.AutoField(db_column='id_emprendimiento', primary_key=True, serialize=False)),
                ('latitude', models.CharField(blank=True, db_column='latitud', max_length=45, null=True)),
                ('length', models.CharField(blank=True, db_column='longitud', max_length=45, null=True)),
                ('code', models.CharField(blank=True, db_column='codigo', max_length=45, null=True)),
                ('address', models.CharField(blank=True, db_column='direccion', max_length=45, null=True)),
                ('status', models.CharField(blank=True, db_column='status', max_length=2, null=True)),
                ('activity_eco', models.ForeignKey(db_column='id_actividad_economica', on_delete=django.db.models.deletion.DO_NOTHING, to='entrepreneur.activityeconomic')),
                ('entrepreneur', models.ForeignKey(db_column='id_emprendedor', on_delete=django.db.models.deletion.DO_NOTHING, to='emprendedor.entrepreneur')),
                ('student', models.ForeignKey(db_column='id_estudiante', on_delete=django.db.models.deletion.DO_NOTHING, to='estudiante.student')),
            ],
            options={
                'db_table': 'tbl_emprendimiento',
            },
        ),
        migrations.CreateModel(
            name='MiesStorageValidated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_base_mies', models.IntegerField(blank=True, db_column='#-Base-MIES', null=True)),
                ('identify', models.TextField(blank=True, db_column='CEDULA', null=True)),
                ('names', models.TextField(blank=True, db_column='APELLIDOS Y NOMBRES', null=True)),
                ('phone', models.TextField(blank=True, db_column='TELEFONO', null=True)),
                ('email', models.TextField(blank=True, db_column='Correos electronicos', null=True)),
                ('sector', models.TextField(blank=True, db_column='SECTOR', null=True)),
                ('neighborhood', models.TextField(blank=True, db_column='Barrio', null=True)),
                ('address', models.TextField(blank=True, db_column='Domicilio', null=True)),
                ('type_act_econ', models.TextField(blank=True, db_column='TipoActEcon', null=True)),
                ('economic_activity', models.TextField(blank=True, db_column='ACTIVIDAD ECONOMICA', null=True)),
                ('is_active', models.TextField(blank=True, db_column='Act-Activa', null=True)),
                ('bond_reception_date', models.TextField(blank=True, db_column='FECHA de RECEPCION DE BONO', null=True)),
                ('observations_mies', models.TextField(blank=True, db_column='OBSERVACIONES MIES', null=True)),
                ('observations_sociology', models.TextField(blank=True, db_column='OBSERVACIONES SOCIOLOGIA', null=True)),
                ('student_sociology', models.TextField(blank=True, db_column='Estudiante  Sociologia', null=True)),
            ],
            options={
                'db_table': 'stage_mies_validada',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(db_column='id_permiso', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='titulo', max_length=45)),
                ('description', models.CharField(db_column='descripcion', max_length=45)),
                ('status', models.CharField(db_column='status', max_length=45)),
            ],
            options={
                'db_table': 'tbl_permiso',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(db_column='id_rol', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nombre_rol', max_length=45)),
                ('description', models.CharField(db_column='descripcion', max_length=45)),
            ],
            options={
                'db_table': 'tbl_rol',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('id_rol', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, to='entrepreneur.role')),
                ('permission_id', models.ForeignKey(db_column='permission_id', on_delete=django.db.models.deletion.CASCADE, to='entrepreneur.permission')),
            ],
            options={
                'db_table': 'tbl_rol_permiso',
            },
        ),
        migrations.CreateModel(
            name='Observations',
            fields=[
                ('id', models.AutoField(db_column='idt_obs_mies', primary_key=True, serialize=False)),
                ('detail', models.CharField(blank=True, db_column='detalle', max_length=45, null=True)),
                ('type_observation', models.CharField(blank=True, db_column='tipo_observacion', max_length=45, null=True)),
                ('entrepreneurship', models.ForeignKey(db_column='id_emprendimiento', on_delete=django.db.models.deletion.DO_NOTHING, to='entrepreneur.entrepreneurship')),
            ],
            options={
                'db_table': 'tbl_observaciones',
            },
        ),
        migrations.CreateModel(
            name='LogGeneral',
            fields=[
                ('id', models.AutoField(db_column='id_log_general', primary_key=True, serialize=False)),
                ('event', models.DateTimeField(db_column='event_time')),
                ('host', models.TextField(db_column='HOST')),
                ('mac', models.TextField(db_column='MAC')),
                ('end_time', models.DateTimeField(blank=True, db_column='end_time', null=True)),
                ('user_data_base', models.CharField(blank=True, db_column='user_data_base', max_length=45, null=True)),
                ('request', models.JSONField(blank=True, db_column='request', null=True)),
                ('sql_text', models.TextField(blank=True, db_column='sql_text', null=True)),
                ('response', models.JSONField(blank=True, db_column='response', null=True)),
                ('latitude', models.CharField(blank=True, db_column='latitud', max_length=45, null=True)),
                ('length', models.CharField(blank=True, db_column='longitud', max_length=45, null=True)),
                ('user', models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_log_general',
            },
        ),
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.AutoField(db_column='id_bono', primary_key=True, serialize=False)),
                ('date_reception', models.DateField(blank=True, db_column='fecha_recepcion', null=True)),
                ('value', models.FloatField(blank=True, db_column='valor', null=True)),
                ('description', models.CharField(blank=True, db_column='descripcion', max_length=45, null=True)),
                ('entrepreneurship', models.ForeignKey(db_column='id_emprendimiento', on_delete=django.db.models.deletion.CASCADE, to='entrepreneur.entrepreneurship')),
            ],
            options={
                'db_table': 'tbl_bono',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.DO_NOTHING, to='entrepreneur.role'),
        ),
    ]
