# Generated by Django 3.2.4 on 2021-09-09 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeActivityEconomic',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, db_column='nombre', max_length=45, null=True)),
                ('description', models.CharField(blank=True, db_column='descripcion', max_length=45, null=True)),
            ],
            options={
                'db_table': 'tbl_tipo_actividad_economica',
            },
        ),
    ]
